import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header/Header";
import TipeeButton from "@/components/admin/TipeeButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <main>{children}</main>
        {/* Bouton Tipeee fixe en bas à droite */}
        <div className="fixed bottom-6 left-6 z-50">
          <TipeeButton
            tipeeUrl="https://fr.tipeee.com/fmonline/"
            username="VotrePseudo"
            size="md"
            variant="gradient"
            className="shadow-2xl hover:shadow-3xl transition-shadow duration-300"
          />
        </div>
      </body>
    </html>
  );
}
